// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfepflbrzswxjqavwpmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmZXBmbGJyenN3eGpxYXZ3cG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjQwODMsImV4cCI6MjA2MTAwMDA4M30.srvE75zhf-OBGzY1AT8baBDFbsR5SM-8E_Ka_bsiY6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);